#!/usr/bin/env python3
"""Validate the planning-only Reduced NC DIS Phase 2 roadmap artifacts."""

from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path
from typing import Any

ROADMAP_PATH = "docs/reduced_nc_dis/phase2_roadmap.json"
SPEC_PATH = "docs/reduced_nc_dis/contracts/phase2a_contract_review_spec.json"
CLOSEOUT_PATH = "docs/phase1b_closeout_manifest.json"

ROADMAP_SCHEMA = "partonsbi.phase2.reduced-nc-dis-roadmap.v1"
SPEC_SCHEMA = "partonsbi.phase2a.reduced-nc-dis-contract-review-spec.v1"
MAIN_COMMIT = "c264eac23be09a91b09ac5b924aa1a079171ffcd"
CLOSEOUT_SCHEMA = "partonsbi.phase1b.closeout-manifest.v2"
CLOSEOUT_SHA256 = "ea509c228aa74021af15c5e1473b257dd0c1b6863118ac9f4be484358c7c8fd5"

HIGH_LEVEL_QUESTION = (
    "Can continuous PDF deformations be constrained from unbinned DIS event "
    "sets using amortized simulation-based inference?"
)
OPERATIONAL_QUESTION = (
    "Can amortized simulation-based inference produce calibrated posterior "
    "constraints on continuous PDF deformations from unbinned neutral-current "
    "DIS event sets generated by an explicit, normalized, detector-aware reduced "
    "observation model?"
)

PHASE_IDS = ["Phase2", "Phase2A", "Phase2B", "Phase2C", "Phase2D", "Phase2E", "Phase2F", "Phase2G", "Phase2H"]
ISSUE_NUMBERS = list(range(53, 62))
EXPECTED_EDGES = {
    ("Phase2A", "Phase2B"),
    ("Phase2B", "Phase2C"),
    ("Phase2C", "Phase2D"),
    ("Phase2D", "Phase2E"),
    ("Phase2E", "Phase2F"),
    ("Phase2F", "Phase2G"),
    ("Phase2F", "Phase2H"),
}

NONCLAIMS = {
    "full PYTHIA equivalence",
    "showering",
    "ISR",
    "hadronization",
    "beam-remnant modelling",
    "underlying-event modelling",
    "complete collider-event realism",
    "production-grade detector simulation",
    "unrestricted full-flavor PDF determination",
    "replacement of a global PDF fit",
    "legacy D2 completion",
    "full-generator closure",
}

ALLOWED_CLAIMS = {
    "set-level amortized inference",
    "continuous PDF deformation inference",
    "an explicit normalized NC DIS observation law",
    "unbinned event-set inference",
    "detector-aware inference through a normalized kernel",
    "posterior calibration and repeated-sampling coverage",
    "proof-of-principle sensitivity under a declared reduced model",
}

OBLIGATION_IDS = [
    "EXACT_E_MINUS_NC_FORMULA",
    "EXACT_E_PLUS_NC_FORMULA",
    "F2_FL_XF3_CONVENTIONS",
    "GAMMA_Z_INTERFERENCE_AND_SIGNS",
    "ELECTROWEAK_INPUT_SCHEME",
    "FACTORIZATION_AND_RENORMALIZATION_SCALES",
    "FLAVOR_AND_HEAVY_QUARK_SCHEME",
    "PDF_FAMILY_AND_TRANSPORT_IDENTITY",
    "KINEMATIC_COORDINATES_AND_JACOBIAN",
    "ACCEPTANCE_REGION_DEFINITION",
    "STRICT_PDF_SUPPORT_INTERSECTION",
    "FINITE_NONZERO_NORMALIZATION_FOR_EVERY_THETA",
    "NONNEGATIVE_COMPLETE_DIFFERENTIAL_RATE",
    "FIXED_N_SHAPE_ONLY_OBSERVATION_LAW",
    "RATE_INCLUSIVE_EXTENSION_SEPARATED",
    "NORMALIZED_DETECTOR_MARKOV_KERNEL",
    "PERFECT_DETECTOR_IDENTITY_KERNEL",
    "OBSERVED_FEATURE_AND_LEAKAGE_CONTRACT",
    "EXPLICIT_OMITTED_PHYSICS_DECLARATION",
    "INDEPENDENT_NUMERICAL_CLOSURE_PLAN",
    "POSTERIOR_TARGET_AND_PROPER_TRAINING_OBJECTIVE",
    "CALIBRATION_COVERAGE_AND_FAILURE_CRITERIA",
]

OBLIGATION_FIELDS = {
    "obligation_id",
    "status",
    "scientific_question",
    "required_primary_evidence",
    "required_equations_or_definitions",
    "required_validation",
    "pass_condition",
    "fail_condition",
    "implementation_dependency",
    "limitations",
}

TRUE_AUTHORIZATION_FLAGS = {
    "PHASE2_ROADMAP_AUTHORIZED",
    "PHASE2A_CONTRACT_REVIEW_AUTHORIZED",
    "PHASE2A_PRIMARY_SOURCE_REVIEW_AUTHORIZED",
}

FALSE_AUTHORIZATION_FLAGS = {
    "IMPLEMENTATION_AUTHORIZED",
    "PROTOTYPE_AUTHORIZED",
    "PDF_FAMILY_REDESIGN_AUTHORIZED",
    "LOWER_LEVEL_SIMULATOR_AUTHORIZED",
    "WEIGHTED_SET_OBJECTIVE_AUTHORIZED",
    "SIGNED_WEIGHT_RESEARCH_AUTHORIZED",
    "PYTHIA_INIT_AUTHORIZED",
    "PYTHIA_NEXT_AUTHORIZED",
    "EVENT_GENERATION_AUTHORIZED",
    "DATASET_AUTHORIZED",
    "NEURAL_TRAINING_AUTHORIZED",
    "D2_AUTHORIZED",
    "PHASE2B_AUTHORIZED",
    "PHASE2C_AUTHORIZED",
    "PHASE2D_AUTHORIZED",
    "PHASE2E_AUTHORIZED",
    "PHASE2F_AUTHORIZED",
    "PHASE2G_AUTHORIZED",
    "PHASE2H_AUTHORIZED",
    "REDUCED_NC_DIS_IMPLEMENTATION_AUTHORIZED",
    "NUMERICAL_PHYSICS_AUTHORIZED",
    "SAMPLER_IMPLEMENTATION_AUTHORIZED",
    "DETECTOR_IMPLEMENTATION_AUTHORIZED",
    "TRAINING_AUTHORIZED",
}

SPLIT_TRIGGERS = [
    "The reduced simulator becomes useful outside PartonSBI.",
    "The reduced simulator requires an independent public API and semantic versioning.",
    "Multiple downstream projects depend on the reduced simulator.",
    "The reduced simulator needs an independent release and governance cycle.",
    "Simulator development becomes scientifically independent of PDF posterior inference.",
]

PLANNED_DIRS = (
    "src/reduced_nc_dis",
    "analysis/reduced_nc_dis",
    "tests/reduced_nc_dis",
)


class RoadmapValidationError(ValueError):
    """Raised when the roadmap violates a binding planning invariant."""


def require(condition: bool, message: str) -> None:
    if not condition:
        raise RoadmapValidationError(message)


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def graph_is_acyclic(nodes: set[str], edges: set[tuple[str, str]]) -> bool:
    successors = {node: set() for node in nodes}
    indegree = {node: 0 for node in nodes}
    for source, target in edges:
        if source not in nodes or target not in nodes:
            return False
        successors[source].add(target)
        indegree[target] += 1
    ready = [node for node, degree in indegree.items() if degree == 0]
    visited = 0
    while ready:
        node = ready.pop()
        visited += 1
        for target in successors[node]:
            indegree[target] -= 1
            if indegree[target] == 0:
                ready.append(target)
    return visited == len(nodes)


def validate_roadmap(roadmap: dict[str, Any], spec: dict[str, Any], root: Path, *, verify_files: bool = True) -> None:
    required_sections = {
        "schema_version", "generated_from_main", "predecessor_closeout", "user_authorized_direction",
        "research_objective", "operational_research_question", "paper_scope", "nonclaims",
        "repository_strategy", "split_triggers", "planned_repository_layout", "legacy_line", "phases",
        "dependency_graph", "github_roadmap_snapshot", "milestone", "labels", "project_fields",
        "authorization", "next_step", "validation",
    }
    require(required_sections <= roadmap.keys(), "roadmap is missing a required top-level section")
    require(roadmap["schema_version"] == ROADMAP_SCHEMA, "roadmap schema mismatch")
    require(roadmap["generated_from_main"] == MAIN_COMMIT, "generated main identity changed")

    predecessor = roadmap["predecessor_closeout"]
    require(predecessor["main_commit"] == MAIN_COMMIT, "predecessor main commit changed")
    require(predecessor["closeout_schema"] == CLOSEOUT_SCHEMA, "predecessor closeout schema changed")
    require(predecessor["closeout_manifest_sha256"] == CLOSEOUT_SHA256, "predecessor closeout hash changed")
    require(predecessor["immutable_historical_snapshot"] is True, "closeout is not immutable")
    require("subsequent user-authorized planning decision" in predecessor["statement"], "closeout chronology changed")
    if verify_files:
        require(sha256(root / CLOSEOUT_PATH) == CLOSEOUT_SHA256, "Phase 1B closeout manifest bytes changed")
        require(load_json(root / CLOSEOUT_PATH)["schema_version"] == CLOSEOUT_SCHEMA, "live closeout schema changed")

    direction = roadmap["user_authorized_direction"]
    require(direction == {
        "REPOSITORY_STRATEGY": "KEEP_IN_PARTON_SBI",
        "OVERARCHING_RESEARCH_OBJECTIVE": "PRESERVE_SET_LEVEL_PDF_SBI_OBJECTIVE",
        "NEW_RESEARCH_LINE": "REDUCED_NORMALIZED_NC_DIS_OBSERVATION_MODEL",
        "PAPER_SCOPE": "PROOF_OF_PRINCIPLE_METHODOLOGY",
        "FULL_GENERATOR_CLAIM": "NOT_MADE",
        "PHASE2A_PLANNING_AUTHORIZED": True,
        "PHASE_2A_IS_NOT_LEGACY_D2": True,
    }, "user-authorized direction changed")

    objective = roadmap["research_objective"]
    require(objective["question"] == HIGH_LEVEL_QUESTION, "high-level research question changed")
    require(objective["inference_unit"] == "D = {y_1, ..., y_N}", "set inference unit changed")
    require(objective["target"] == "p(theta_PDF | D)", "posterior target changed")
    require(objective["set_level"] is True, "set-level objective disabled")
    require(objective["single_event_instantaneous_pdf_objective"] is False, "one-event instantaneous PDF claim enabled")
    require(objective["unrestricted_full_flavor_separation_claimed"] is False, "full-flavor separation claim enabled")
    require(roadmap["operational_research_question"] == OPERATIONAL_QUESTION, "operational research question changed")
    require(roadmap["paper_scope"]["scope"] == "PROOF_OF_PRINCIPLE_METHODOLOGY", "paper scope expanded")
    require(set(roadmap["paper_scope"]["claims_allowed_only_if_later_validated"]) == ALLOWED_CLAIMS, "paper claim boundary changed")
    require(set(roadmap["nonclaims"]) == NONCLAIMS, "required nonclaims changed")

    strategy = roadmap["repository_strategy"]
    require(strategy["CURRENT_REPOSITORY"] == "parton-sbi", "current repository changed")
    require(strategy["CURRENT_ARCHITECTURE"] == "MONOREPO_WITH_INDEPENDENT_RESEARCH_LINE", "repository architecture changed")
    require(strategy["REPOSITORY_STRATEGY"] == "KEEP_IN_PARTON_SBI", "same-repository decision changed")
    require(strategy["new_repository_created"] is False, "new repository is claimed")
    require(strategy["repository_split_active"] is False and strategy["repository_split_authorized"] is False, "repository split activated")
    require(strategy["preferred_implementation_architecture"] is None, "preferred implementation architecture selected")
    require(strategy["preferred_implementation_architecture_selected"] is False, "implementation architecture selection flag enabled")
    require(roadmap["split_triggers"] == SPLIT_TRIGGERS, "repository split triggers changed")

    layout = roadmap["planned_repository_layout"]
    require(layout["created"] is False and layout["no_code_directory_claimed_to_exist"] is True, "planned code layout claimed as created")
    require(layout["creation_requires_separate_phase_authorization"] is True, "future code layout authorization weakened")
    if verify_files:
        for relative in PLANNED_DIRS:
            require(not (root / relative).exists(), f"forbidden planning-phase code directory exists: {relative}")

    legacy = roadmap["legacy_line"]
    require(legacy["D1F_FINAL_DECISION"] == "MAINTAIN_CURRENT_CONTRACT_AND_PAUSE", "D1F decision changed")
    require(legacy["D1G_FINAL_DECISION"] == "NO_UNIQUE_PRIORITY_MAINTAIN_PAUSE", "D1G decision changed")
    require(legacy["D1G_ELIGIBLE_CANDIDATES"] == [], "D1G candidates changed")
    require(legacy["ACTIVE_OPERATIONAL_POLICY"] == "PAUSE_GENERATOR_COUPLING_WITHOUT_AUTHORIZATION", "legacy policy changed")
    require(legacy["CURRENT_FULL_GENERATOR_LINE"] == "PAUSED_NO_BOUNDED_CONTINUATION_ESTABLISHED", "full-generator line activated")
    require(legacy["LEGACY_D2_AUTHORIZED"] is False, "legacy D2 authorized")
    require(legacy["legacy_D2_status"] == "Blocked", "legacy D2 is not blocked")
    require(legacy["old_full_generator_roadmap_superseded"] is False, "legacy roadmap superseded")
    require(legacy["PHASE_2A_IS_NOT_LEGACY_D2"] is True, "Phase 2A treated as legacy D2")
    require(legacy["issue_10"] == {
        "issue_number": 10, "state": "OPEN", "status": "Blocked", "gate_decision": "Not Evaluated",
        "authorization": "Not Authorized", "modified_by_phase2_bootstrap": False,
    }, "issue #10 state changed")

    phases = roadmap["phases"]
    require(len(phases) == 9, "roadmap must contain exactly nine issues")
    require([phase["phase_id"] for phase in phases] == PHASE_IDS, "phase inventory changed")
    issue_numbers = [phase["issue_number"] for phase in phases]
    require(issue_numbers == ISSUE_NUMBERS, "roadmap issue numbers changed")
    require(len(set(issue_numbers)) == 9, "roadmap issue numbers are not unique")
    phase_fields = {"phase_id", "issue_number", "title", "purpose", "deliverables", "binding_gate", "blockers", "downstream", "status", "authorization", "priority", "required_for_mvp", "implementation_allowed"}
    for phase in phases:
        require(phase_fields <= phase.keys(), f"{phase.get('phase_id')} lacks a required phase field")
        require(phase["implementation_allowed"] is False, f"{phase['phase_id']} permits implementation")
    require(phases[1]["authorization"] == "Planning Only", "Phase 2A is not planning-only")
    require(all(phase["authorization"] == "Not Authorized" for phase in phases[2:]), "later phase authorization enabled")
    require(phases[-1]["required_for_mvp"] is False, "Phase 2H made mandatory for MVP")

    edges = {(edge["from"], edge["to"]) for edge in roadmap["dependency_graph"]["edges"]}
    require(edges == EXPECTED_EDGES, "dependency graph changed")
    require(graph_is_acyclic(set(PHASE_IDS[1:]), edges), "dependency graph is cyclic or references an unknown stage")
    require(roadmap["dependency_graph"]["acyclic"] is True, "DAG flag changed")
    require(roadmap["dependency_graph"]["phase2h_blocks_phase2g"] is False, "Phase 2H blocks Phase 2G")
    require(roadmap["dependency_graph"]["phase2g_requires_phase2h"] is False, "Phase 2G requires Phase 2H")
    require("Phase2H" not in phases[7]["blockers"], "Phase 2G phase record depends on Phase 2H")

    snapshot = roadmap["github_roadmap_snapshot"]
    require(snapshot["observed_at_utc"].endswith("Z"), "GitHub snapshot timestamp missing")
    require(snapshot["source"] == "GITHUB_API_AND_PROJECT_V2_GRAPHQL", "GitHub snapshot source changed")
    require(snapshot["offline_validator_can_verify_live_github_state"] is False, "offline validator claims live GitHub verification")
    require(snapshot["issue_numbers"] == dict(zip(PHASE_IDS, ISSUE_NUMBERS)), "GitHub issue snapshot changed")
    require(snapshot["project_number"] == 2 and snapshot["project_id"] == "PVT_kwHOB6bw_s4BeowZ", "Project identity changed")
    require(len(snapshot["project_items"]) == 9, "GitHub snapshot must contain nine Project items")
    for item in snapshot["project_items"]:
        require(item["Research Line"] == "Reduced NC DIS", "new issue lacks Reduced NC DIS Research Line")
        require(item["Gate Decision"] == "Not Evaluated", "new issue gate evaluated prematurely")
    require(snapshot["native_relationships_verified"] is True, "native dependency verification missing")
    require(len(snapshot["native_sub_issue_links"]) == 8, "native sub-issue snapshot incomplete")
    require(len(snapshot["native_blocked_by_links"]) == 7, "native dependency snapshot incomplete")
    require(snapshot["labels"] == ["phase2", "reduced-nc-dis", "planning-only"], "label snapshot changed")
    require(roadmap["milestone"]["number"] == 1 and roadmap["milestone"]["due_date"] is None, "milestone identity or due date changed")
    require(roadmap["project_fields"].get("field_value_source") == "TIMESTAMPED_GITHUB_PROJECT_V2_SNAPSHOT", "Project field provenance missing")
    require(roadmap["project_fields"]["Research Line"]["historical_items_bulk_edited"] is False, "historical Project items were bulk edited")
    require(roadmap["project_fields"]["Research Line"]["issue_10_modified"] is False, "issue #10 Project fields changed")

    authorization = roadmap["authorization"]
    require(set(authorization) == TRUE_AUTHORIZATION_FLAGS | FALSE_AUTHORIZATION_FLAGS, "authorization matrix fields changed")
    require({key for key, value in authorization.items() if value is True} == TRUE_AUTHORIZATION_FLAGS, "only roadmap and Phase 2A review flags may be true")
    require(all(authorization[key] is False for key in FALSE_AUTHORIZATION_FLAGS), "an implementation or later-phase flag is true")
    require(roadmap["next_step"] == "PHASE2A_SOURCE_BACKED_CONTRACT_REVIEW_ONLY", "next step exceeds Phase 2A review")
    require(roadmap["validation"]["offline_validator_can_verify_live_github_state"] is False, "validation claims live GitHub verification")
    require(roadmap["validation"]["scientific_observation_law_validated"] is False, "observation law claimed validated")

    validate_spec(spec)


def validate_spec(spec: dict[str, Any]) -> None:
    required_sections = {
        "schema_version", "decision", "scientific_gate", "research_question", "inference_target",
        "latent_variables", "observed_variables", "fixed_n_shape_only_baseline", "optional_rate_extension_boundary",
        "proof_obligations", "source_requirements", "go_no_go_rules", "nonclaims", "authorization", "next_step", "validation",
    }
    require(required_sections <= spec.keys(), "Phase 2A spec is missing a required section")
    require(spec["schema_version"] == SPEC_SCHEMA, "Phase 2A spec schema mismatch")
    require(spec["decision"] == "CONTRACT_REVIEW_SPECIFIED_PLANNING_ONLY", "Phase 2A planning decision changed")
    require(spec["scientific_gate"] == "NOT_EVALUATED", "Phase 2A scientific gate evaluated prematurely")
    require(spec["research_question"] == OPERATIONAL_QUESTION, "Phase 2A research question changed")
    require(spec["inference_target"]["target"] == "p(theta_PDF | D)", "Phase 2A posterior target changed")
    require(spec["inference_target"]["single_event_instantaneous_pdf_objective"] is False, "Phase 2A permits one-event instantaneous inference")

    baseline = spec["fixed_n_shape_only_baseline"]
    for key in ("fixed_n", "shape_only", "unbinned", "set_level", "detector_aware", "amortized_posterior_inference"):
        require(baseline[key] is True, f"baseline property disabled: {key}")
    require(baseline["weighted_events"] is False and baseline["signed_weights"] is False, "weighted baseline enabled")
    require(baseline["count_or_rate_likelihood_included"] is False, "rate semantics mixed into baseline")
    require("integral_A" in baseline["latent_law"], "normalized latent law missing")

    rate = spec["optional_rate_extension_boundary"]
    require(rate["separate_from_baseline"] is True and rate["required_for_mvp"] is False, "rate extension merged into MVP")
    require(rate["requires_separate_observation_law"] is True, "rate extension lacks a separate law")
    require(rate["may_silently_change_phase2e_objective"] is False, "rate extension may silently alter Phase 2E")

    obligations = spec["proof_obligations"]
    require(len(obligations) == 22, "Phase 2A must contain exactly 22 obligations")
    require([item["obligation_id"] for item in obligations] == OBLIGATION_IDS, "Phase 2A obligation inventory changed")
    for item in obligations:
        require(set(item) == OBLIGATION_FIELDS, f"{item.get('obligation_id')} fields changed")
        require(item["status"] == "NOT_EVALUATED", f"{item['obligation_id']} was evaluated prematurely")

    require(len(spec["source_requirements"]) == 6, "primary-source requirement inventory changed")
    rules = spec["go_no_go_rules"]
    require(rules["pass_requires_all_independently_supported"] == [
        "exact_formula_contract", "finite_positive_normalization_reviewability", "posterior_target_coherence",
        "strict_support_contract", "normalized_detector_kernel_contract", "no_hidden_clipping",
        "fixed_n_shape_only_semantics", "bounded_phase2b_validation_plan", "paper_claim_boundary_consistency",
    ], "Phase 2A PASS requirements changed")
    require(rules["if_any_required_item_not_supported"] == "PHASE2A_DECISION = FAIL", "FAIL rule changed")
    require(rules["if_required_evidence_missing"] == "PHASE2A_DECISION = INCONCLUSIVE", "INCONCLUSIVE rule changed")
    require(rules["pass_authorizes"] == "A_SEPARATE_PHASE2B_PROPOSAL_ONLY", "PASS authorization expanded")
    require(rules["pass_directly_authorizes_implementation"] is False, "PASS directly authorizes implementation")
    require(set(spec["nonclaims"]) == NONCLAIMS, "Phase 2A nonclaims changed")
    require(spec["next_step"] == "PHASE2A_SOURCE_BACKED_CONTRACT_REVIEW_ONLY", "Phase 2A next step changed")
    require(spec["validation"]["scientific_correctness_validated"] is False, "spec claims scientific correctness")


def main() -> int:
    root = Path(__file__).resolve().parents[1]
    roadmap = load_json(root / ROADMAP_PATH)
    spec = load_json(root / SPEC_PATH)
    validate_roadmap(roadmap, spec, root, verify_files=True)
    print(
        f"VALID {ROADMAP_SCHEMA} issues={len(roadmap['phases'])} "
        f"obligations={len(spec['proof_obligations'])} offline_live_github=false"
    )
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (RoadmapValidationError, KeyError, TypeError, json.JSONDecodeError) as exc:
        print(f"INVALID: {exc}", file=sys.stderr)
        raise SystemExit(1) from exc
